### ISSUE TITLE
Oh My Zsh & cgr

### ISSUE THREAD

**Issue by taylorotwell** [consolidation-org/cgr#1]
One thing you may wish to note in the installation documentation is that "oh-my-zsh"'s "composer" plug-in creates a shell alias "cgr" which resolves to "composer global require". If a developer is using oh-my-zsh and this plugin, they may be confused as to why "cgr" is still just doing a regular "composer global require".

Anyways, not sure if it's common enough to warrant a note in the documentation, but maybe a note to verify that "which cgr" is actually pointing to what you think it is might be helpful.

Thanks for the great tool!

**Comment by greg-1-anderson** [comment]
Thanks for pointing that out -- I updated the README to contain a troubleshooting section with this info.
